openapi: 3.0.1
info:
  title: Open Caching API - CDNI schema extended with SVA Open Caching  objects and properties
  description: 'This is the CDNI schema required to ellaborate an Open Caching API model as exposed by an ISP according to the Streaming Video Alliance (SVA).'
  contact:
    email: guillaume.bichot@broadpeak.tv
  version: 0.1.0
externalDocs:
    description: Find out more
    url: 'https://www.streamingvideoalliance.org/'
components:
  schemas:
    FCI_capabilitytype_SVA:
          enum: [FCI.Logging.sva, FCI.Capacity.sva]
    FCI_genericbase:
      oneOf:
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI_genericbase'
        - type: object
          description: 'adding properties to the FCI_genericbase object'
          required:
            - capability-type
            - capability-value
          properties:
            capability-type:
              $ref: '#/components/schemas/FCI_capabilitytype_SVA'
            capability-value:
              oneOf:
                - $ref: '#/components/schemas/FCI.Metadata'
                - $ref: '#/components/schemas/FCI.Logging.sva'
                - $ref: '#/components/schemas/FCI.Capacity.sva'
              discriminator: 
                propertyName: capability-type
            footprints:
              type: array
              description: 'List of CDNI Footprint objects (from the "CDNI Metadata Footprint Types" registry [RFC8006])'
              items:
                $ref: '#/components/schemas/MI.Footprint'
    FCI.Metadata:
      type: object
      description: 'extension of CDNI FCI.Metadata'
      required:
        - metadata
      properties:
        metadata:
          description: 'List of supported CDNI GenericMetadata types. List of strings corresponding to entries from the "CDNI
         Payload Types" registry [RFC7736] that correspond to CDNI GenericMetadata objects. An empty list MUST be interpreted as 
         "no GenericMetadata types are supported", i.e., "only structural metadata and simple types are supported"; otherwise, the list
         must be interpreted as containing "the only GenericMetadata types that are supported" (in addition to structural metadata and simple types) [RFC8006].'
          type: array
          items: 
            allOf:
              - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_payloadtype'
              - $ref: '#/components/schemas/MI_payloadtype_SVA'
    FCI.Logging.sva:
      type: object
      description: 'The SVA Logging capability object is used to indicate support for CDNI Logging record-types, 
      as well as CDNI and SVA Logging fields that are marked as optional for the specified record-types [RFC7937].'
      required:
        - record-type
      properties:
        transport-types:
          description: 'list of supported protocols for logs injection'
          type: array
          items:
            type: object
            description: 'possibly one protocol for one region'
            required:
              - transport
            properties:
              footprint:
                $ref: '#/components/schemas/MI.Footprint'    
              transport:
                $ref: '#/components/schemas/MI_Loggingtransporttype_SVA'
        record-type: 
          description: 'log record format/type supported'
          allOf:
            - $ref: '#/components/schemas/MI_Loggingrecordtype_SVA'
        fields:
          description: 'List of supported CDNI and SVA Logging fields that are optional for the specified record-type.
          Default is that all optional fields are supported.  Omission of this field MUST be interpreted as "all optional fields are supported".  
          An empty list MUST be interpreted as "no optional fields are supported".  Otherwise, if a list of fields is provided, 
          the fields in that list MUST be interpreted as "the only optional fields that are supported".'
          type: array 
          items: 
            oneOf:
              - $ref: '#/components/schemas/MI_Loggingfieldname'
              - $ref: '#/components/schemas/MI_Loggingfieldname_SVA'
            discriminator:
              propertyName: record-type
              mapping:
                cdni_http_request_v1: '#/components/schemas/MI_Loggingfieldname'
                sva_http_request_v1: '#/components/schemas/MI_Loggingfieldname_SVA'
        hash-fields:
          description: 'List of fields that are obfuscated'
          type: array 
          items: 
            oneOf:
              - $ref: '#/components/schemas/MI_Loggingfieldname'
              - $ref: '#/components/schemas/MI_Loggingfieldname_SVA'
            discriminator:
              propertyName: record-type
              mapping:
                cdni_http_request_v1: '#/components/schemas/MI_Loggingfieldname'
                sva_http_request_v1: '#/components/schemas/MI_Loggingfieldname_SVA'
    FCI.Capacity.sva:
      description: 'capacity capabilities'
      oneOf:
        - $ref: '#/components/schemas/MI.Capacity.sva'
# MI extensions
    MI.Footprint:
      oneOf:
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Footprint'
        - type: object
          properties:
            footprint-type:
              $ref: '#/components/schemas/MI_footprinttype_SVA'
            footprint-value:
              oneOf:
                - $ref: '#/components/schemas/MI_gpsrectangle_SVA'
              discriminator:
                propertyName: footprint-type
    MI_footprinttype_SVA:
      type: string
      enum: [gps]
    MI_gpsrectangle_SVA:
      description: 'A rectangle surface expressed as an array of two GPS points (left/upper and right/bottom)' 
      type: array
      minItems: 2
      maxItems: 2
      items: 
        $ref: '#/components/schemas/MI_gps_sva'
    MI_gps_sva:
      type: object
      description: 'GPS coordinates'
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
    MI_payloadtype_SVA:
      type: string
      enum: [MI.Logging.sva, MI.Capacity.sva]
    MI_GenericMetadata:
      oneOf:
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_GenericMetadata'
        - type: object
          description: 'GenericMetadata object extension by SVA'
          required:
            - generic-metadata-type
            - generic-metadata-value
          properties:
            generic-metadata-type:
              $ref: '#/components/schemas/MI_payloadtype_SVA'
            generic-metadata-value:
              oneOf:
                - $ref: '#/components/schemas/MI.RedirectionMode.sva'
                - $ref: '#/components/schemas/MI.Logging.sva'
                - $ref: '#/components/schemas/MI.Capacity.sva'       
              discriminator: 
                propertyName: generic-metadata-type
            mandatory-to-enforce:
              type: boolean
              description: 'Flag identifying whether or not the enforcement of the property metadata is required.'
              default: true
            safe-to-redistribute:
              type: boolean
              description: 'Flag identifying whether or not the property metadata can be safely redistributed without modification.'
              default: true
            incomprehensible:
              type: boolean
              description: 'Flag identifying whether or not any CDN in the chain of delegation has failed to understand and/or failed to properly transform 
              this metadata object.  Note: This flag only applies to metadata objects whose safe-to-redistribute property has a value of False.'
    MI.RedirectionMode.sva:
      type: object
      description: 'indicates the redirection mode, for what footprints and potential associated parameters (none for now)' 
      required:
        - type
      properties:
        type:
          $ref: 'SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI_redirectionmode'
        footprints:
          type: array
          items:
            $ref: '#/components/schemas/MI.Footprint'
    MI.Logging.sva:
      type: object
      description: 'logging configuration according to SVA (supersedes CDNI)'
      properties:
        record-type:
          $ref: '#/components/schemas/MI_Loggingrecordtype_SVA'
        include-fields:
          description: 'The default for “fields” property is that all optional fields are included. 
          Omission of this property MUST be interpreted as "all". An empty list corrresponds to "None of the fields".'
          type: array
          items:
            discriminator:
              propertyName: record-type
              mapping:
                cdni_http_request_v1: '#/components/schemas/MI_Loggingfieldname'
                sva_http_request_v1: '#/components/schemas/MI_Loggingfieldname_SVA'
        exclude-fields:
          description: 'The default for “fields” property is that none of optional fields are exluded. 
          Omission of this property MUST be interpreted as "none". An empty list corrresponds to "all of the fields are excluded".'
          type: array
          items:
            discriminator:
              propertyName: record-type
              mapping:
                cdni_http_request_v1: '#/components/schemas/MI_Loggingfieldname'
                sva_http_request_v1: '#/components/schemas/MI_Loggingfieldname_SVA'
        transport-protocols:
          description: 'list of supported protocols for logs injection. Possibly one protocol for one region'
          type: array
          items:
            type: object
            required:
              - transport
            properties:
              footprint:
                $ref: '#/components/schemas/MI.Footprint'   
              transport-type: 
                description: 'the configuration parameters of the transport protocol depends on the type of protocol'
                allOf:
                  - $ref: '#/components/schemas/MI_Loggingtransporttype_SVA'
              transport_parameters:
                discriminator:
                  propertyName: transport-type
                  mapping: 
                    cdni: '#/components/schemas/MI_Loggingtransportcdni_SVA'
                    kafka: '#/components/schemas/MI_Loggingtransportkafka_SVA'
                    logstash: '#/components/schemas/MI_Loggingtransportlogstash_SVA'
    MI_Loggingtransportcdni_SVA:
      type: string
      enum: [none]
    MI_Loggingtransportkafka_SVA:
      type: string
      enum: [none]
    MI_Loggingtransportlogstash_SVA:
      type: string
      enum: [none]
    MI_Loggingtransporttype_SVA:
      type: string
      enum: [cdni, kafka, logstash]
    MI_Loggingrecordtype_SVA:
      type: string
      enum: [cdni_http_request_v1, sva_http_request_v1]
    MI_Loggingfieldname:
      type: string
      enum: [date, time, time-taken, c-groupid, s-ip, s-hostname, s-port, cs-uri, u-uri, protocol, 
      sc-status, sc-total-bytes, sc-entity-bytes, cs(insert_HTTP_header_name_here), sc(insert_HTTP_header_name_here), s-ccid, s-sid, s-cached ]
    MI_Loggingfieldname_SVA:
      type: string
      enum: [time, duration, client-adress, result-codes, bytes, request-method, url, hierarchy-code, type, 
      host-name, source-name, cache-key, aborted, error-codes_CND]
    MI.Capacity.sva:
      type: object
      description: 'capacity interface configuration'
      required:
        - capacities
      properties:
        capacities:
          description: 'An array with footprints and associated capacity type to listen'
          type: array
          items:
            $ref: '#/components/schemas/MI_Capacity_SVA'
    MI_Capacity_SVA:    
      type: object
      description: 'a footprint entry associated with a capacity configuration.'
      required:
        - capacity-type
      properties:  
        footprint:
          description: 'the surrogates caches concerned by the capacity inquiry/monitoring'
          type: array
          items:
            $ref: '#/components/schemas/MI.Footprint'
        capacity-type:
          description: 'the type of capacity'
          type: array
          items:
            $ref: '#/components/schemas/MI_capacitytype_SVA'
    MI_capacitytype_SVA:
      type: object
      properties:
        source:
          description: 'capacity source'
          type: string
          enum: [storage, bandwidth]
        unit:
          type: string
          enum: [ratio, kbps, kB]

# Metadata exposed by the dCDN/ISP
    MId.HostIndex:
      type: object
      description: 'The HostIndex object as configured by the uCDN'
      required:
        - hosts
      properties:
        hosts:
          type: array
          items:
            $ref: '#/components/schemas/MId.HostMatch'
          description: 'Array of HostMatch objects'
    MId.HostMatch:
      type: object
      required:
        - host
        - host-metadata
      properties:
        host:
          allOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint'
          description: 'Hostname or IP address and optional port to match against the requested host, i.e., the host and port as described in [RFC3986]. 
          In order for a hostname or IP address in a content request to match the hostname or IP address in the "host" property, 
          the value from the content request when converted to lowercase MUST be identical to the value of the "host" property when converted to lowercase.  
          All implementations MUST support IPv4 addresses encoded as specified by the "IPv4address" rule in Section 3.2.2 of [RFC3986]. 
          IPv6 addresses MUST be encoded in one of the IPv6 address formats specified in [RFC5952], although receivers MUST support 
          all IPv6 address formats specified in [RFC4291]. Hostnames MUST conform to the Domain Name System (DNS) syntax defined in [RFC1034] and [RFC1123].  
          Internationalized Domain Names (IDNs) must first be transformed to the A-label form [RFC5890] as per [RFC5891]'
        host-metadata:
          type: array
          items:
            $ref: '#/components/schemas/MId_GenericMetadata'
          description: 'Metadata to apply when delivering content that matches this host'
    MId_GenericMetadata:
      type: object
      description: 'A GenericMetadata object attached to the dCDN/ISP'
      required:
        - generic-metadata-type
        - generic-metadata-value
      properties:
        generic-metadata-type:
          $ref: '#/components/schemas/MId_payloadtype'
        generic-metadata-value:
          oneOf:
            - $ref: '#/components/schemas/MId.RedirectTarget'
          discriminator: 
            propertyName: generic-metadata-type
    MId_payloadtype:
      type: string
      enum: [MId.HostIndex, MId.HostMatch, MId.RedirectTarget, MId.Logging]
    MId.Logging:
      type: object
      description: 'retrieve the configuration established by the dCDN/ISP regarding logging after having processed some related metadata'
      properties:
        pull-url: 
          description: 'the URL associated with a PULL mechnaism used to retrieve the logs (e.g. CDNI RFC 7937)'
          oneOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint'
    MId.RedirectTarget:
      type: object
      description: 'Extension per RFC8004'
      properties:
        redirecting-hosts:
          description: 'One or more uCDN hosts to which this redirect target is attached.  A redirecting host SHOULD be a host that was 
          published in a HostMatch object by the uCDN as defined in Section 4.1.2 of [RFC8006]'
          type: array
          items:
             $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint'
        dns-target:
          description: 'The DnsTarget object gives the target address for the DNS response to delegate from the uCDN to the dCDN.'
          allOf:
            - $ref: '#/components/schemas/MId_dnstarget'
        http-target:
          description: 'Target URI for an HTTP redirect.'
          allOf:
            - $ref: '#/components/schemas/MId_httptarget'
    MId_httptarget:
      type: object
      description: 'FCI extension per RFC8004: the HttpTarget object gives the necessary information to construct the target Location URI for HTTP redirection.'    
      required:
        - host
      properties:
        host: 
          description: 'Hostname or IP address and an optional port, i.e., the host and port of the authority component of the URI as
         described in Section 3.2 of [RFC3986].'
          allOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint'
        scheme:
          description: 'A URI scheme to be used in the redirect response location construction.  When present, the uCDN MUST use the 
          provided scheme in for HTTP redirection to the dCDN.'
          type: string
          enum: [http, https]
        path-prefix:
          description: 'A path prefix for the HTTP redirect Location header. The original path is appended after this prefix.'
          type: string
        include-redirecting-host:
          description: 'A flag indicating whether or not to include the redirecting host as the first path segment after the path-prefix. 
          If set to true and a "path-prefix" is used, the uCDN redirecting host MUST be added as a separate path segment after the path-prefix 
          and before the original URL path.  If set to true and there is no path-prefix, the uCDN redirecting host MUST be prepended as
           the first path segment in the redirect URL.'
          type: boolean
          default: false
    MId_dnstarget:
      type: object
      description: 'FCI extension per RFC8004: the DnsTarget object gives the target address for the DNS response to delegate from the uCDN to the dCDN.'    
      required:
        - host
      properties:
        host:
          description: 'Endpoint object as defined in Section 4.3.3 of [RFC8006], with the limitation that it SHOULD NOT include 
          a port number and, in case a port number is present, the uCDN MUST ignore it.'
          allOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint' 