openapi: 3.0.1
info:
  title: Open Caching API - CONfiguration Interface (COI) - 2c- Cache Control
  description: 'This is the Open Caching API model as exposed by an ISP( dCDN) according to the Streaming Video Technology Alliance (SVTA). It provides metadata objects definition for cache control configuration.'
  contact:
    email: guillaume.bichot@broadpeak.tv
  version: 2.0.0
externalDocs:
    description: 'Corresponding SVTA 2033 specification'
    url: 'https://www.svta.org/product/svta2033-1'
components:
  schemas:
# MI objects
    MI_COI2c_payloadtype:
      type: string
      enum: [MI.CachePolicy, MI.NegativeCachePolicy, MI.StaleContentCachePolicy, MI.ComputedCacheKey, MI.CacheBypassPolicy]
    MI_COI2c_payloadvalue:
      oneOf:
        - $ref: '#/components/schemas/MI.CachePolicy'
        - $ref: '#/components/schemas/MI.NegativeCachePolicy'
        - $ref: '#/components/schemas/MI.StaleContentCachePolicy'   
        - $ref: '#/components/schemas/MI.ComputedCacheKey'
        - $ref: '#/components/schemas/MI.CacheBypassPolicy'
    MI_CachePolicy:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.CachePolicy'
    MI_cachepolicy_iors:
      oneOf:
        - type: string
          enum: ["as-is", "no-cache", "no-store"]
        - type: integer
      default: "as-is"
    MI.CachePolicy:
      type: object
      properties:
        internal:  
          description: 'This property is used to specify the (internal) cache control policy to be used by the dCDN.The value of the cache policy is in seconds, for example "5" is a five second cache. The following special values are also supported: "as-is", "no-cache", "no-store". If not used, the default is to use the cache control policy specified in the HTTP response from the uCDN.' 
          $ref: '#/components/schemas/MI_cachepolicy_iors'
        external:  
          description: 'This property is used to specify the (external) cache control policy to be used by clients of this dCDN. The value of the cache policy is in seconds. The following special values are also supported: "as-is", "no-cache", "no-store". "no-cache". If not used, the default is to use the cache control policy specified in the HTTP response from the uCDN.'
          $ref: '#/components/schemas/MI_cachepolicy_iors'
        force-internal:  
          description: 'If set to True, the metadata interface cache policy defined in the MI.CachePolicy internal property value will override any cache control policy set in the response from the uCDN. If set to False, the MI.CachePolicy internal property value is only used if there is no cache control policy provided in the response from the uCDN. The default is False, which will apply the MI.CachePolicy internal property value only if no policy is provided in the response from the uCDN.'
          type: boolean
          default: false
        force-external:  
          description: 'If set to True, the metadata interface cache policy defined in the MI.CachePolicy external property value will override any cache control policy set in the response from the uCDN. If set to False, the MI.CachePolicy external property value is only used if there is no cache control policy provided in the response from the uCDN. The default is False, which will apply the MI.CachePolicy external property value only if no policy is provided in the response from the uCDN.'
          type: boolean
          default: false
      example:
        value:  {
                  "internal": "as-is",
                  "external": "no-cache",
                  "force-internal": true,
                  "force-external": true
                  }
    MI_NegativeCachePolicy:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.NegativeCachePolicy'
    MI.NegativeCachePolicy: 
      type: object
      description: 'Allows for the configuration of caching policies based on error response codes received from the origin.'
      required:
        - cache-policy
      properties:
        error-codes:
          description: 'Array of HTTP response error status codes (https://tools.ietf.org/html/rfc7231#page-47), that if returned from the uCDN, will be cached using the cache policy defined in cache-policy. By default the policy expressed in RFC8006 is applied. An empty or unspecified list may function as a means to revoke a list inherited from an upper level configuration.'
          type: array
          items:
            type: string
            description: Any HTTP status code from 100 to 599, or one of the special values  "4xx" or "5xx", where "xx" implies everything from 00 to 99. Note that use of 4xx would specify that 416 responses are cached.
        cache-policy:
          description: 'MI.CachePolicy to apply to the HTTP response error status codes returned by the uCDN.'
          $ref: '#/components/schemas/MI_CachePolicy'
      example:
        value: {
          "error-codes": ["404", "503", "504"],
          "cache-policy": {
            "internal": 5,
            "external": "no-cache",
            "force-internal": true,
            "force-external": true
            }
          }
    MI_StaleContentCachePolicy:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.StaleContentCachePolicy'
    MI.StaleContentCachePolicy:
      type: object
      description: 'Allows the uCDN to specify the policy to use by a dCDN when responding with stale (expired) content.'
      properties: 
        stale-while-revalidating:
          description: 'This property is used to instruct the dCDN to serve a stale version of a resource while refreshing the resource with the uCDN. When set to True, the dCDN will return a previously cached version of a resource while the resource is refreshed with the uCDN in the background. The default is False, which waits for the uCDN to refresh a resource before responding to the client.'
          type: boolean
          default: false
        stale-if-error:
          description: 'Instructs the dCDN to serve a stale version of a resource if any one of a specified set of HTTP status codes was received when trying to refresh the resource with the uCDN.  In this case, the dCDN will return a previously cached version of a resource instead of caching the error response. While this capability is typically used for well-understood HTTP error status codes, a list of any HTTP codes can be provided for maximum flexibility. The default is to not serve stale content.  An empty or unspecified list may function as a means to revoke a list inherited from an upper level configuration If specified, the  stale-if-error list must not be empty.'
          type: array 
          items:
            type: string
            description: Any HTTP status code from 100 to 599, or one of the special values  "4xx" or "5xx", where "xx" implies everything from 00 to 99.
        failed-revalidation-delta-seconds:
          description: 'Drives the dCDN behavior when revalidation attempts to the uCDN fail, specifying the number of seconds to wait before making another attempt to revalidate the resource with the uCDN. Use of failed-revalidation-delta-seconds allows load to be reduced on the uCDN during times of system stress. Stale content is served during this wait period.'
          type: integer
          default: 0
      example:
        value: {
                "stale-while-revalidating": "true", 
                "stale-if-error": ["404", "503", "504" ],
                "failed-revalidation-delta-seconds ": 5
              }
    MI_ComputedCacheKey:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.ComputedCacheKey'
    MI.ComputedCacheKey:
      type: object
      required:
        - expression
      properties:
        expression:
          description: 'An expression using CDNI-MEL to dynamically construct the cache key from elements of the HTTP request and/or response.'
          type: string
      example:
        value: {
          "expression" : "req.h.X-Cache-Key",
          }
    MI_CacheBypassPolicy:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.CacheBypassPolicy'
    MI.CacheBypassPolicy:
      type: object
      description: 'Allows a client request to be set as non-cacheable.  It is expected that this feature will be used to allow clients to test the fill path to the uCDN. Any content previously cached (by client requests that do not set MI.CacheBypassPolicy) MUST NOT be evicted'
      properties:
        bypass-cache:
          description: 'A Boolean value that can activate the feature for a given client request.  It is expected that this feature will be used within ProcessingStages to allow a client request to be marked to bypass a cache.'
          type: boolean
          default: false