openapi: 3.0.1
info:
  title: Open Caching API - Bootstrap Interface (BOI)
  description: 'This is the Open Caching API model as exposed by an ISP( dCDN) according to the Streaming Video Technology Alliance (SVTA). The Bootstrap API exposes the list of supported interfaces and for each interface, the list of supported versions.'
  contact:
    email: guillaume.bichot@broadpeak.tv
  version: 1.0.0
externalDocs:
    description: 'Corresponding SVTA 2060 specification' 
    url: 'https://www.svta.org/product/svta2060'
security: 
  - bearerToken: []
paths:
  /OC/bootstrap/bootstrap:
    get:
      tags:
        - OC_BSB
      summary: 'The bootstrap API entry point. Expose the bootstrap API versions and their respective entry points.'
      operationId: oc_bs_get_bootstrap
      responses:
        '200':
          description: 'Open Caching bootstrap API entry point.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BSI.Bootstrap'
        '400':
          description: 'Bad request.'
        '403':
          description: 'Forbidden.'
        '404':
          description: 'No bootstrap'
  /OC/{bootstrap_api_version}/bootstrap/version:
    get:
      tags:
        - OC_BSI
      summary: 'Discover the dCDN OpenCaching exposed API information.'
      operationId: oc_bs_get_bootstrap_version
      parameters:
        - name: bootstrap_api_version
          in: path
          required: true
          description: 'URL Path part related to the bootstrap API version.'
          schema:
            type: string
      responses:
        '200':
          description: 'Open Caching API version.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BSI.OpenCachingVersions'
        '400':
          description: 'Bad request.'
        '403':
          description: 'Forbidden.'
        '404':
          description: 'No bootstrap version API'
components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BSI.Bootstrap:
      type: object
      description: 'Describe the version number attached with the bootstrap API; it must be compliant with the following form: "<Major>.<minor>.<patch>".'
      required:
        - bsi
      properties:
        bsi: 
          description: 'Bootstrap API version(s)'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
    BSI.OpenCachingVersions:
      type: object
      description: 'Describe the version number attached with each implemented and exposed Open Caching interface. A version number  must be compliant with the following form: "<Major>.<minor>.<patch>".'
      required: 
        - fci
      properties:
        open-caching:
          description: 'SVA Open Caching API version description. This is for information purpose. The format is not constraint and should not follow the "<Major>.<minor>.<patch>" pattern.'
          type: string
        fci: 
          description: 'Footprint and Capabilities Interface version.'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
        coi: 
          description: 'Configuration interface version.'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
        rri: 
          description: 'Request Routing Interface version.'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
        cmi:
          description: 'Content Management Interface version.'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
        loi: 
          description: 'Logging Interface version.'
          type: array
          items:
            $ref: '#/components/schemas/BSI_version'
    BSI_version:
      type: object
      description: 'An object that gathers a version number and the corresponding URL.'
      required:
        - number
        - url
      properties:
        number:
          type: string
          description: 'It must be compliant with the following form: "<Major>.<minor>.<patch>".'
        url:  
          type: string
          description: 'The Interface API end point URL exposed by the dCDN corresponding to the version number. The URL may be used as is or may be completed with a path prefix depending on interface.'