openapi: 3.0.1
info:
  title: Open Caching API - Request Routing Interface (RRI) 
  description: 'This is the Open Caching API model as exposed by an ISP( dCDN) according to the Streaming Video Technology Alliance (SVTA). It gathers metadata configuration objects definition, protocol objects definition and FCI related objects definition.'
  contact:
    email: guillaume.bichot@broadpeak.tv
  version: 1.0.0
externalDocs:
    description: 'Corresponding SVTA 2048 specification'
    url: 'https://www.svta.org/product/2048/'
security: 
  - bearerToken: []
paths:
  /OC/RRI/{object}:
    parameters:
      - name: object
        in: path
        description: 'the user requested object including the path part'
        required: true
        schema:
          type: string
          format: url-path-style
    get:
      tags:
        - OC_RRI
      summary: Routing Request API for delegation in recursive mode (request-driven session from SVTA2048).
      operationId: OC_RRI_requestdriven
      responses:
        200:
          description: 'Returns the requested object.'
          content:
            {} 
        302:
          description: ''
          headers: 
            Location:
              schema:
                type: string
                format: url        
        307:
          description: ''
          headers: 
            Location:
              schema:
                type: string
                format: url
        400:
          description: 'Command is invalid.'
        403:
          description: 'Forbidden.'
        404:
          description: 'Not found.'
        425:
          description: 'Too early.'
        500:
          description: ''
          content:
            'application/cdni':
              schema:
                $ref: '#/components/schemas/RI_error'      
    post:
      tags:
        - OC_RRI
      summary: Routing Request API for delegation in recursive mode (reponse-driven session from SVTA2048).
      operationId: OC_RRI_responsedriven
      requestBody:
        description: 'The object communicated by the uCDN, fetched from the origin and possibly modified'
        content:
          {}
        required: true
      responses:
        200:
          description: 'Returns the POST request body object, possibly modified.'
          content:
            {}
        302:
          description: ''
          headers: 
            Location:
              schema:
                type: string
                format: url
        307:
          description: ''
          headers: 
            Location:
              schema:
                type: string
                format: url
        400:
          description: 'Command is invalid.'
        403:
          description: 'Forbidden.'
        404:
          description: 'Not found.'
        500:
          description: ''
          content:
            'application/cdni':
              schema:
                $ref: '#/components/schemas/RI_error'  
  /OC/RRI/routing_request:
    post:
      tags:
        - OC_RRI
      summary: Routing Request API for DNS or HTTP redirect method in recursive mode (RFC 7975).
      description: 'Simplification applies regarding RFC 7975. There is no CDN traversal and therfore no loop possible. Only one uCDN and one dCDN/ISP.'
      operationId: OC_RRI_routingrequest
      requestBody:
        description: 'The request according to RFC 7975.'
        content:
          application/cdni;ptype=redirection-request:
            schema:
              description: 'per RFC7975'
              $ref: '#/components/schemas/RI.Request'
        required: true
      responses:
        200:
          description: The RI request is ok.
          content:
            application/cdni;ptype=redirection-response:
              schema:
                description: 'The reponse that contains information about the redirection target or an error to be used for building the response to the user agent.'
                $ref: '#/components/schemas/RI.Response'
        400:
          description: Command is invalid.
        403:
          description: Forbidden.
        404:
          description: Not found.
components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
  # FCI
    FCI_RRI_capabilitytype:
      type: string
      enum: [FCI.RequestRoutingInterface, FCI.RequestRoutingInterfaceTarget ]
    FCI_RRI_capabilityvalue:
      oneOf:
        - $ref: '#/components/schemas/FCI.RequestRoutingInterface'
        - $ref: '#/components/schemas/FCI.RequestRoutingInterfaceTarget'
    FCI.RequestRoutingInterface:
      type: object
      description: 'To advertize about the dCDN Request Routing Interface endpoint'
      required:
        - protocol
      properties:
        forwarding-hosts:
          description: 'One or more uCDN hosts to which this request routing interface is attached. A forwarding host SHALL be a host that was published in a HostMatch object by the uCDN, as defined in Section 4.1.2 of [RFC8006].'
          type: array
          items:
             $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_endpoint'
        request-router-target:
          description: 'target URI of the dCDN request router exposing the Request Routing Interface.'
          $ref: '#/components/schemas/FCI.RequestRoutingInterfaceTarget'
        protocol:
          description: 'The supported request routing interface protocol.'
          type: array
          items:
            type: string
            enum: ["RFC7975", "OC_RECURSIVE"]
        oc-recursive-start:
          description: 'The way to initiate an OC-RECURSIVE session. By default, request mode is assumed.'
          type: string
          enum: ["Request", "Response"]
        oc-recursive-http-methods:
          description: 'A list of HTTP request methods supported. By default, only GET is supported.'
          type: array
          items:
            type: string
            enum: ["GET", "OPTIONS", "HEAD"]
        http-version: 
          description: 'A list of supported HTTP versions in the user request (i.e., between the user agent and the uCND RR). Unsupported versions should not be forwarded to the dCDN RR. By default, HTTP1.x is assumed.'
          type: array
          items:
            type: string
            enum: ["HTTP1.x", "HTTP2", "HTTP3"]
    FCI.RequestRoutingInterfaceTarget:
      type: object
      description: 'The request routing interface target object gives the necessary information to construct the target URI for HTTP forwarding.'
      required:
        - host
      properties:
        host: 
          description: 'Hostname or IP address and an optional port, i.e., the host and port of the authority component of the URI as described in Section 3.2 of [RFC3986].'
          $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_endpoint'
        path-prefix:
          description: 'A prefix of a path-absolute as defined in Section 3.3 of [RFC3986]. The prefix MUST end with a trailing slash to indicate the end of the last path segment in the prefix. If this property is absent or empty, the uCDN MUST NOT prepend a path-prefix to the original content path.'
          type: string
        include-forwarding-host:
          description: 'A flag indicating whether or not to include the forwarding host as the first path segment after the path-prefix (if any). If set to true and a "path-prefix" is used, the uCDN forwarding host MUST be added as a separate path segment after the path-prefix and before the original URL path.  If set to true and there is no path-prefix, the uCDN forwarding host MUST be prepended as the first path segment in the forwarding URL.'
          type: boolean
          default: false
# RI
    RI_ipaddress:
      type: string
    RI_uri:
      type: string
    RI_method:
      type: string
      enum: [GET, HEAD, OPTIONS]
    RI_iprange:
      type: array
      items:
        $ref: '#/components/schemas/RI_cidr'
    RI_cidr:
      oneOf:
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_ipv4cidr'
        - $ref: './SVTA_OC_openAPI_COI.yaml#/components/schemas/MI_ipv6cidr'
    RI_qtype:
      type: string
      enum: [A, AAAA]
    RI_qclass:
      type: string
      enum: [IN]
    RI_error:
      description: 'Per RFC7975 / section 4.7.'
      type: object
      required:
        - error-code
      properties:
        error-code:
          type: integer
          enum: [100, 400, 500, 501, 502, 503, 504, 505, 506]
        reason:
          type: string
          description: "Reason associated with each of the error-code value as indicated in RFC7975 / section 4.7."
    RI.Request:
      type: object
      description: 'dns or http property is required. not both'
      required:
        - cdn-path
      properties:
        dns:
          $ref: '#/components/schemas/RI_dnsredirectionrequest'
        http:
          $ref: '#/components/schemas/RI_httpredirectionrequest'
        cdn-path:
          description: 'No CDN traversal in SVA. The cdn-path MUST be reflected back in RI response and MUST contain the value of cdn-path received in the associated RI request with the final dCDNs CDN Provider ID appended.'
          type: array
          items: 
            type: string
        max-hops:
          type: integer
      example: 
        value: { 
          "http": {
            "c-ip": "198.51.100.1",
            "cs-uri": "http://www.example.com/manifest.mpd",
            "cs-version": "HTTP/1.1",
            "cs-method": "GET",
            },
          "cdn-path": ["AS64496:0"],
          "max-hops": 1
          }
    RI.Response:
      type: object
      description: 'dns or http property is required. not both'
      properties:
        dns:
          $ref: '#/components/schemas/RI_dnsredirectionresponse' 
        http:
          $ref: '#/components/schemas/RI_httpredirectionresponse'
        scope:
          $ref: '#/components/schemas/RI_iprange'
        error:
          $ref: '#/components/schemas/RI_error'
      example: 
        value: { 
          "http": {
            "sc-status": 307,
            "sc-version": "HTTP/1.1",
            "sc-reason": "Found",
            "cs-uri": "http://www.example.com/manifest.mpd",
            "sc-(location)": "http://ocn3.dCDN.com:8090/www.example.com/manifest.mpd"
              },
          "error": {
          "error-code": 100,
          "description": "This is a human-readable message meant for debugging purposes"
            }
          }
    RI_dnsredirectionrequest:
      type: object
      required:
        - resolver-ip
        - qtype
        - qclass
        - qname
      properties:
        resolver-ip: 
          $ref: '#/components/schemas/RI_ipaddress'
          description: 'The IP address of the UA DNS resolver'
        qtype:
          $ref: '#/components/schemas/RI_qtype'
          description: 'The type of Query made by the UA DNS resolver'
        qclass:
          $ref: '#/components/schemas/RI_qclass'
          description: 'The DNS class of the query made by the UA DNS resolver '
        qname:
          type: string
          description: 'The FQDN being quieried'
        c-subnet:
          $ref: '#/components/schemas/RI_iprange'
          description: 'The IP address (or prefix) of the UA in Classless Inter-Domain Routing (CIDR) format.'
    RI_httpredirectionrequest:
      type: object
      required:
        - c-ip
        - cs-uri
        - cs-method
        - cs-version
      properties:
        c-ip: 
          $ref: '#/components/schemas/RI_ipaddress'
          description: 'The IP address of the User Agent'
        cs-uri:
          $ref: '#/components/schemas/RI_uri'
          description: 'The URI ([RFC7230]) requested by the User Agent'
        cs-method:
          $ref: '#/components/schemas/RI_method'
          description: 'The HTTP method part of the request line (Section 3.1.1 of [RFC7230]) '
        cs-version:
          $ref: '#/components/schemas/RI_version'
          description: 'The HTTP-version part of the request line (as defined in section 3.1.1 of RFC7230])'
    RI_statuscodes:
      type: integer
      enum: [302, 303, 307]
    RI_version:
      type: string
      enum: [HTTP/1.1, HTTP/2, HTTP/3]
    RI_reason:
      type: string
    RI_httpredirectionresponse:
      type: object
      required:
        - sc-status
        - sc-version
        - sc-reason
        - cs-uri
        - sc-(location)
      properties:
        sc-status: 
          $ref: '#/components/schemas/RI_statuscodes'
          description: 'The status-code part of the status-line as defined in Section 3.1.2 of [RFC7230] to return to the UA (usually set to 302).'
        sc-version:
          $ref: '#/components/schemas/RI_version'
          description: 'The HTTP-version part of the status-line as defined in Section 3.1.2 of [RFC7230] to return to the UA .'
        sc-reason:
          $ref: '#/components/schemas/RI_reason'
          description: 'The reason-phrase part of the status-line as defined in Section 3.1.2 of [RFC7230] to return to the UA '
        cs-uri:
          $ref: '#/components/schemas/RI_uri'
          description: 'The URI ([RFC7230]) requested by the User Agent'
        sc-(location):
          $ref: '#/components/schemas/RI_uri'
          description: 'The content of the Location header to return to the UA: the URI ([RFC7230]) pointing to the redirect target (i.e. the OCN)'
    RI_rcode:
      type: integer
      enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 17, 18, 19, 20, 21, 22]
    RI_dnsredirectionresponse:
      type: object
      description: 'MUST include at least one of the following keys: a, aaaa, or cname'
      required:
        - rcode
        - name
      properties:
        rcode: 
          $ref: '#/components/schemas/RI_rcode'
          description: 'DNS response code [RFC6895]).'
        name:
          type: string
          description: 'The FQDN the response relates to'
        a:
          type: array
          items:
            $ref: '#/components/schemas/RI_ipaddress'
          description: 'IPv4 address(es) of the redirect target'
        aaaa:
          type: array
          items:
            $ref: '#/components/schemas/RI_ipaddress'
          description: 'IPv6 address(es) of the redirect target'
        cname :
          type: array
          items:
            type: string
          description: 'one (or more)  FQDN name(s) corresponding to the redirect target(s)'
        ttl:
          description: 'TTL in seconds of the DNS response'
          type: integer
          default: 0